name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: This is a brand new tests
      id: this-is-a-brand-new-tests
      uses: education/autograding-command-grader@v1
      with:
        test-name: This is a brand new tests
        setup-command: ''
        command: ''
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        THIS-IS-A-BRAND-NEW-TESTS_RESULTS: "${{steps.this-is-a-brand-new-tests.outputs.result}}"
      with:
        runners: this-is-a-brand-new-tests
